CREATE DATABASE GatePassDB;
USE GatePassDB;

CREATE TABLE GatePassRequests (
    RequestID INT PRIMARY KEY AUTO_INCREMENT,
    StudentName VARCHAR(100),
    FromPlace VARCHAR(100) NOT NULL,
    ToPlace VARCHAR(100) NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    RequestDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
